server:
  port: 8081

spring:
  application:
    name: partner-gold-api

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

springdoc:
  swagger-ui:
    path: /swagger-ui.html
